### ISSUE TITLE
Keeps crashing and not recovering

### ISSUE THREAD

**Issue by shoei600** [cosote/ha-async-tcp-proxy#1]
Dear all,
I'm running this modus proxy in Home Assistant and it works fine when it works, but at least twice per day it crashes and does not recover. I have setup an auto-start automation so when data becomes null or not correct, it attempts to restart this 'add on'.

I believe my SolarEdge inverter is the cause of the issue on IP address 131 in the error log below, but I have not had any issues at all with Solaredge Modbus which had been running for many months before I replaced comms with this module. 

192,168.1.131 is Solaredge Inverter
192.168.1.132 is Home Assistant which also hosts this modus proxy

Each crash leaves my system without any PV data and I have lost a lot already. IF I manually restart the module in HA, everything works again. How can this be made robust/reliable please?

Thanks.

ERROR LOG:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Preparing to run async-tcp-proxy
Server: 192.168.1.131:1502
Server timeout: 1
Client timeout: 1
Loglevel: INFO
Execute: python async-tcp-proxy.py --port 8899 --server-host 192.168.1.131 --server-port 1502 --server-timeout 1 --client-timeout 1 --loglevel INFO
2023-11-07 18:21:19,900 - root - INFO - TCP proxy server started on port 8899
2023-11-07 18:21:23,392 - 192.168.1.132:50175 - INFO - New client connection
2023-11-07 18:21:23,394 - 192.168.1.132:50175 - ERROR - Error connecting to remote server: [Errno 111] Connect call failed ('192.168.1.131', 1502)
2023-11-07 18:21:23,394 - 192.168.1.132:50175 - INFO - Closing client connection, reason: unknown
2023-11-07 18:21:23,394 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=TypeError('cannot unpack non-iterable NoneType object')>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-11-07 18:21:24,198 - 192.168.1.132:52749 - INFO - New client connection
2023-11-07 18:21:24,200 - 192.168.1.132:52749 - ERROR - Error connecting to remote server: [Errno 111] Connect call failed ('192.168.1.131', 1502)
2023-11-07 18:21:24,200 - 192.168.1.132:52749 - INFO - Closing client connection, reason: unknown
2023-11-07 18:21:24,201 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=TypeError('cannot unpack non-iterable NoneType object')>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-11-07 18:21:26,605 - 192.168.1.132:40791 - INFO - New client connection
2023-11-07 18:21:26,606 - 192.168.1.132:40791 - ERROR - Error connecting to remote server: [Errno 111] Connect call failed ('192.168.1.131', 1502)
2023-11-07 18:21:26,606 - 192.168.1.132:40791 - INFO - Closing client connection, reason: unknown
2023-11-07 18:21:26,607 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=TypeError('cannot unpack non-iterable NoneType object')>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-11-07 18:21:33,810 - 192.168.1.132:47701 - INFO - New client connection

**Comment by cosote** [comment]
Hi @shoei600,
my appoligies that you lost PV data. The network connection issues to your inverter are weired.
I will try to reproduce it on my side and improve the error handling and might consider to let the proxy terminate on server connection issues and have the HA watch-dog restart the addon.
Cheers - cosote.

**Comment by shoei600** [comment]
@cosote Hi, thank you for looking at this. In general it crashes at least 3 times per day and the 'autostart' I have setup for when a value goes null doesn't always bring it back. I ran the Solaredge Modbus library from @willcodeforcats and @remko for many months without a single issue or drop out but I needed other systems to share in the data.  My network is full ubiquiti solution which is very robust.
Thanks.

**Comment by cosote** [comment]
Ok - so, Errno 111 is "just" connection refused from inverter side. Why - no idea, but I could check what other implementation do with that situation like: wait a couple Seconds, or ??? But now I can reproduce it easy, make this little proxy more stable. I think this weekend I have personal time to work on it 👍. Cheers - cosote.

**Comment by cosote** [comment]
@shoei600 Just thinking about the connection refused situation... I have a questions for your setup: Can you assure that no other component is connecting to your inverter via Modbus over TCP or even via serial? This RS485/Modbus 70's protocol is very sensitive: only one master can call out for connected slaves - and your inverter might simply refused this connection, because another connection is processed right now. Anyway, I need to fix areas in the proxy code, but avoiding serial communication collitions is very improtant for even more stable data poll.

**Comment by shoei600** [comment]
@cosote Hi, definitely no other connections, not even via RS485 directly. It been a real problem the past couple of days, I don’t think it has connected much at all. Here’s the log I have from HA, I hope this helps shed some light on what might be going on. Thanks.

TypeError: cannot unpack non-iterable NoneType object
2023-12-07 03:47:42,367 - 192.168.1.132:34603 - INFO - New client connection
2023-12-07 16:58:28,367 - 192.168.1.132:34603 - ERROR - Connection error reading from remote server: [Errno 32] Broken pipe
2023-12-07 16:58:28,368 - 192.168.1.132:34603 - WARNING - Closing remote server connection, reason: [Errno 32] Broken pipe
2023-12-07 16:58:28,368 - 192.168.1.132:34603 - INFO - Closing client connection, reason: Connection error reading from remote server: [Errno 32] Broken pipe
2023-12-07 16:58:29,173 - 192.168.1.132:51877 - INFO - New client connection
2023-12-07 16:58:29,176 - 192.168.1.132:51877 - ERROR - Error connecting to remote server: [Errno 111] Connect call failed ('192.168.1.131', 1502)
2023-12-07 16:58:29,176 - 192.168.1.132:51877 - INFO - Closing client connection, reason: unknown
2023-12-07 16:58:29,178 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-90624' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=TypeError('cannot unpack non-iterable NoneType object')>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-12-07 16:58:31,583 - 192.168.1.132:43153 - INFO - New client connection
2023-12-07 16:58:50,003 - 192.168.1.132:43153 - INFO - Closing client connection, reason: unknown
2023-12-07 16:58:50,004 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-90626' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=OSError(113, "Connect call failed ('192.168.1.131', 1502)")>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//async-tcp-proxy.py", line 29, in get_remote_server_connection
    remote_reader, remote_writer = await asyncio.open_connection(args.server_host, args.server_port)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.131', 1502)
2023-12-07 16:58:52,365 - 192.168.1.132:42667 - INFO - New client connection
2023-12-07 16:58:55,443 - 192.168.1.132:42667 - INFO - Closing client connection, reason: unknown
2023-12-07 16:58:55,444 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-90628' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=OSError(113, "Connect call failed ('192.168.1.131', 1502)")>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//async-tcp-proxy.py", line 29, in get_remote_server_connection
    remote_reader, remote_writer = await asyncio.open_connection(args.server_host, args.server_port)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.131', 1502)
2023-12-07 16:58:56,251 - 192.168.1.132:57775 - INFO - New client connection
2023-12-07 16:58:56,279 - 192.168.1.132:57775 - ERROR - Error connecting to remote server: [Errno 111] Connect call failed ('192.168.1.131', 1502)
2023-12-07 16:58:56,280 - 192.168.1.132:57775 - INFO - Closing client connection, reason: unknown
2023-12-07 16:58:56,281 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-90630' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=TypeError('cannot unpack non-iterable NoneType object')>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-12-07 16:58:58,685 - 192.168.1.132:46557 - INFO - New client connection
2023-12-07 16:58:58,689 - 192.168.1.132:46557 - ERROR - Error connecting to remote server: [Errno 111] Connect call failed ('192.168.1.131', 1502)
2023-12-07 16:58:58,690 - 192.168.1.132:46557 - INFO - Closing client connection, reason: unknown
2023-12-07 16:58:58,691 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-90632' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=TypeError('cannot unpack non-iterable NoneType object')>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-12-07 16:59:05,896 - 192.168.1.132:32937 - INFO - New client connection
2023-12-07 16:59:05,898 - 192.168.1.132:32937 - ERROR - Error connecting to remote server: [Errno 111] Connect call failed ('192.168.1.131', 1502)
2023-12-07 16:59:05,899 - 192.168.1.132:32937 - INFO - Closing client connection, reason: unknown
2023-12-07 16:59:05,899 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-90634' coro=<handle_client() done, defined at //async-tcp-proxy.py:55> exception=TypeError('cannot unpack non-iterable NoneType object')>
Traceback (most recent call last):
  File "//async-tcp-proxy.py", line 69, in handle_client
    remote_reader, remote_writer = await get_remote_server_connection(log)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-12-07 16:59:15,366 - 192.168.1.132:44751 - INFO - New client connection

**Comment by WillCodeForCats** [comment]
Sometimes when the inverter loses connection or if a network error causes it to drop without closing properly, the inverter will hold it for 2 minutes before forcing closed. During that time it will reject connections as if there is still one active.
